Fix testcode
yoshiki105/rspec_app_exam pull request #1
Opened 2021-04-01 08:41 UTC by yoshiki105

RSpec編/課題4/要件に沿って修正完了しました。

・spec/system/task_spec.rb
- ローカル変数を削除し、テストデータの作成にはletを使用するよう変更。

- Project詳細からTask一覧ページにアクセスした場合、Taskが表示されること
別のウィンドウで開いたページを検証できるようにコードを追加。

- Taskを編集した場合、一覧画面で編集後の内容が表示されること
表示時刻の検証にviewと同じメソッドを使用するように変更。

- Taskが削除されること
ページ内の検証でタスクのステータス、締切、Destroyの文字を対象にするよう変更。

・spec/factories/tasks.rb
traitを用いて完了済みのタスクのテストデータを追加。

・spec/rails_helper.rb
viewで使われているメソッドを表示時刻の検証に使用できるよう修正。

2021-04-01 09:27 UTC, yuji91 requested changes
気になった点をコメントしました！

2021-04-01 09:27 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content 'Destroy'
こちらどの様な点が問題で、どの様に修正したのかは説明できますでしょうか？

2021-04-01 09:27 UTC, yuji91 commented on spec/system/task_spec.rb
> +        page.driver.browser.switch_to.window(windows.last)
修正としては問題ないですが、1行でも記載できることは知っておいてください。
```suggestion
        switch_to_window(windows.last)
```

2021-04-01 09:27 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task){ create(:task, project: project) }
ProjectのFactoryで`association`を設定することで、この記載は省略できますね。
```suggestion
  let(:task){ create(:task) }
```

2021-04-01 10:58 UTC, yoshiki105 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content 'Destroy'
FactoryBotのテストデータtaskのtitle属性が'Task'となっていて、ページ内の他の文言と被るため、task.titleは使えません。
task.statusとtask.deadline、'Destroy' は被らないので、こちらで検証しています。
また、FactoryBotのtitle属性を'Task test'などにしてページ内の他の要素と被らないようにしても、テストデータの中身によって検証結果が変わってしまう事になるので良くないと思いました。

2021-04-01 11:20 UTC, yoshiki105 commented on spec/system/task_spec.rb
> +        page.driver.browser.switch_to.window(windows.last)
[54682c2](https://github.com/yoshiki105/rspec_app_exam/pull/1/commits/54682c26880a68858b96a57442a0f7b2b4140ab5) で簡潔な表記に直しました。

2021-04-01 11:22 UTC, yoshiki105 commented on spec/system/task_spec.rb
> +  let(:task){ create(:task, project: project) }
[3fa6615](https://github.com/yoshiki105/rspec_app_exam/pull/1/commits/3fa66153c4981a616f3d95e9b5ff922c9475e2dc) でtasks.rbにassociationを追加しました。

2021-04-01 11:29 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content 'Destroy'
> ページ内の他の文言と被るため、task.titleは使えません。

「ページ内の他の文言と被ってしまう」というパターンは今後も起こり得ると思います。
`page.body`をデバッグしてもらうと想像できると思いますが、画面上で確認する範囲を変更するという視点で考えてみてください。

2021-04-01 11:29 UTC, yuji91 requested changes
追加で１点コメントしました。

2021-04-01 13:28 UTC, yoshiki105 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content 'Destroy'
[5e82ed3](https://github.com/yoshiki105/rspec_app_exam/pull/1/commits/5e82ed338274bfeed8ba5f5900e9a663523df89c) 検証する項目を「tdタグが表示されていない事」に修正しました。

2021-04-02 02:38 UTC, yuji91 requested changes
２点コメントしました！

2021-04-02 02:38 UTC, yuji91 commented on spec/factories/tasks.rb
> +      deadline { Time.current.yesterday }
ここではアプリの仕様上、ステータスを完了にすると登録されるカラムを設定して欲しいです。

2021-04-02 02:38 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).to_not have_css 'td'
`have_css 'td'`だと直感的でなく意図が分かりづらい部分があるので、`task.title`が含まれるかで確認できないか試してください。

「画面上で確認する範囲を変更するという視点」でどこを変更するべきかを考えてみてください。

2021-04-02 03:04 UTC, yoshiki105 commented on spec/factories/tasks.rb
> +      deadline { Time.current.yesterday }
[4c016b4](https://github.com/yoshiki105/rspec_app_exam/pull/1/commits/4c016b4c65a36a1080fed5243819192fb2798a58) で修正しました。

2021-04-02 03:05 UTC, yoshiki105 commented on spec/system/task_spec.rb
> +        expect(page).to_not have_css 'td'
[f56cd7e](https://github.com/yoshiki105/rspec_app_exam/pull/1/commits/f56cd7e7b6fa6400d59fa37e29d600f476b50f6b) で確認する範囲を '.task_list' 内に限定しました。

2021-04-02 03:33 UTC, yuji91 approved these changes
LGTMです！

2021-04-06 01:42 UTC, merged